# Generated by Django 5.0.6 on 2024-09-17 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Identification", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="uploadedimage",
            name="upload_time",
        ),
        migrations.AddField(
            model_name="uploadedimage",
            name="uploaded_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="uploadedimage",
            name="image",
            field=models.ImageField(upload_to="images/"),
        ),
    ]
